tester:
  stage: test
  image: node:18
  coverage: /Lines\s* [:] ([\d\.]+)%/
  extends: .rules
  script:
    - npm ci
    - npm run test:coverage
  artifacts:
    when: always
    reports:
      junit:
        - junit.xml
      coverage_report:
        coverage_format: cobertura
        path: coverage/cobertura-coverage.xml

linter:
  stage: test
  image: node:18
  extends: .rules
  script:
    - npm ci
    - npm run lint

audit:
  allow_failure: true
  stage: test
  image: node:18
  extends: .rules
  script:
    - npm audit
